"""medical-order-agent — ADK agent package generated by transpiler."""

from . import agent  # noqa: F401 — required for `adk run` / `adk web` discovery
from .agent import root_agent

__all__ = ["agent", "root_agent"]
