"""medical-order-agent runner CLI — generated by transpiler."""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import re
import sys
import typing
import uuid
from datetime import datetime
from typing import Annotated, Any, Literal

import pydantic
from pydantic import BaseModel, Field, TypeAdapter, field_validator

from generated_agent.logging_ import configure_logging
from generated_agent.preocr import _build_preocr_prompt, _PreOcrError, _run_preocr

_LOGGER = logging.getLogger(__name__)

_AGENT_TIMEOUT = float(os.environ.get("AGENT_TIMEOUT_SECONDS", "300"))  # seconds, ADR-0008 / AC18
_PREOCR_MCP_TIMEOUT = float(os.environ.get("PREOCR_MCP_TIMEOUT_SECONDS", "10"))  # spec 0010
_PREOCR_MCP_CONNECT_RETRIES = int(os.environ.get("PREOCR_MCP_CONNECT_RETRIES", "1"))
_OCR_MCP_URL = os.environ.get("OCR_MCP_URL", "http://ocr-mcp:8001/sse")

# Error code constants (MAJOR-3 + spec 0010 + spec 0009 Camada B)
_E_AGENT_INPUT_NOT_FOUND = "E_AGENT_INPUT_NOT_FOUND"
_E_AGENT_OUTPUT_INVALID = "E_AGENT_OUTPUT_INVALID"
_E_AGENT_OUTPUT_REPORTED_ERROR = "E_AGENT_OUTPUT_REPORTED_ERROR"
_E_AGENT_TIMEOUT = "E_AGENT_TIMEOUT"
_E_OCR_UNKNOWN_IMAGE = "E_OCR_UNKNOWN_IMAGE"
_E_MCP_UNAVAILABLE = "E_MCP_UNAVAILABLE"


# ---------------------------------------------------------------------------
# Output schema — validates LLM runner result before printing (AC19)
# ---------------------------------------------------------------------------


class ExamResolution(BaseModel):
    """Single exam resolved by the agent."""

    name: str
    code: str
    score: float
    inconclusive: bool = False

    @field_validator("score")
    @classmethod
    def score_in_range(cls, v: float) -> float:
        """Validate score is in [0.0, 1.0]."""
        if not (0.0 <= v <= 1.0):
            msg = f"score must be in [0.0, 1.0], got {v}"
            raise ValueError(msg)
        return v


class RunnerSuccess(BaseModel):
    """Canonical success envelope (spec 0009 Camada B / AC3)."""

    status: Literal["success"] = "success"
    exams: list[ExamResolution]
    appointment_id: str
    scheduled_for: datetime


class RunnerErrorDetail(BaseModel):
    """Inner error payload of RunnerError (spec 0009 Camada B)."""

    code: str
    message: str
    hint: str | None = None


class RunnerError(BaseModel):
    """Canonical error envelope (spec 0009 Camada B / AC4)."""

    status: Literal["error"] = "error"
    error: RunnerErrorDetail


RunnerResult = Annotated[
    RunnerSuccess | RunnerError,
    Field(discriminator="status"),
]

RunnerResultAdapter: TypeAdapter[RunnerSuccess | RunnerError] = TypeAdapter(RunnerResult)


_FENCE_PATTERN = re.compile(
    r"^\s*(?:[^`{]*?)```(?:json|JSON)?\s*(\{.*\})\s*```\s*$",
    re.DOTALL,
)


def _strip_json_fence(raw: str) -> str:
    """Remove markdown code fences around a JSON object.

    Known Gemini 2.5 Pro drift (~30% of responses with structured schemas): the
    model wraps the final JSON in ```json ... ``` despite instructions. This
    helper is deliberately conservative — if no fence is detected, the input is
    returned unchanged so the caller's json.loads still raises a sensible
    JSONDecodeError on genuinely malformed payloads.

    Args:
        raw: Raw text from the agent's final response.

    Returns:
        The inner JSON string if a fence is detected, otherwise raw unchanged.
    """
    match = _FENCE_PATTERN.match(raw)
    if match is not None:
        return match.group(1)
    return raw


# ---------------------------------------------------------------------------
# ASCII table formatter (AC17) — pure function, no Rich, no ANSI
# ---------------------------------------------------------------------------


def format_ascii_table(
    rows: list[tuple[str, str, float, bool]],
    appointment_id: str,
    scheduled_for: datetime | str,
) -> str:
    """Format exam results as a plain ASCII table.

    Args:
        rows: List of (name, code, score, inconclusive) tuples.
        appointment_id: Scheduling API appointment ID.
        scheduled_for: Scheduled datetime (datetime or ISO string).

    Returns:
        Multi-line ASCII string in the exact format required by AC17.
    """
    col_widths = [3, 22, 9]  # #, Exame, Codigo — minimum widths
    for i, (name, code, _, _) in enumerate(rows):
        col_widths[0] = max(col_widths[0], len(str(i + 1)))
        col_widths[1] = max(col_widths[1], len(name))
        col_widths[2] = max(col_widths[2], len(code))

    def _sep() -> str:
        return (
            "+"
            + "-" * (col_widths[0] + 2)
            + "+"
            + "-" * (col_widths[1] + 2)
            + "+"
            + "-" * (col_widths[2] + 2)
            + "+"
        )

    def _row(a: str, b: str, c: str) -> str:
        return (
            "| "
            + a.ljust(col_widths[0])
            + " | "
            + b.ljust(col_widths[1])
            + " | "
            + c.ljust(col_widths[2])
            + " |"
        )

    lines: list[str] = [
        _sep(),
        _row("#", "Exame", "Codigo"),
        _sep(),
    ]
    for i, (name, code, score, inconclusive) in enumerate(rows):
        label = code if not inconclusive else f"{code}?"
        lines.append(_row(str(i + 1), name, label))
    lines.append(_sep())

    sched_str = (
        scheduled_for.isoformat()
        if isinstance(scheduled_for, datetime)
        else str(scheduled_for)
    )
    lines.append(f"Appointment ID: {appointment_id}  |  Scheduled: {sched_str}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Error helpers (MAJOR-1: NoReturn + correlation_id in envelope)
# ---------------------------------------------------------------------------


def _exit_error(
    code: str,
    message: str,
    correlation_id: str,
    hint: str | None = None,
    exit_code: int = 1,
) -> typing.NoReturn:
    """Print canonical error envelope to stderr and exit.

    Envelope shape matches ADR-0008 / scheduling_api ErrorEnvelope:
        {"error": {"code": ..., "message": ..., "hint": ...}, "correlation_id": ...}

    Args:
        code: E_* error code per ADR-0008.
        message: Human-readable error message.
        correlation_id: UUID from main() scope for traceability.
        hint: Optional corrective-action hint.
        exit_code: Process exit code (1=input, 2=timeout, 3=output, default=1).
    """
    envelope: dict[str, Any] = {
        "error": {
            "code": code,
            "message": message,
            "hint": hint,
        },
        "correlation_id": correlation_id,
    }
    print(json.dumps(envelope, ensure_ascii=False), file=sys.stderr)
    sys.exit(exit_code)


# ---------------------------------------------------------------------------
# Argument parser (MINOR-9: --spec removed — not wired up)
# ---------------------------------------------------------------------------


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments.

    Returns:
        Parsed namespace with .image attribute.
    """
    parser = argparse.ArgumentParser(
        description="medical-order-agent — ADK agent runner (generated by transpiler)",
    )
    parser.add_argument(
        "--image",
        required=True,
        help="Path to the medical order image (PNG/JPEG).",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Agent runner (BLOCKER-1: inline_data Blob, BLOCKER-2: factory, MAJOR-4: cleanup)
# ---------------------------------------------------------------------------


async def _run_agent(exams: list[str], correlation_id: str) -> Any:
    """Run the ADK agent with a text-only prompt containing the exam list.

    Pre-OCR (spec 0010 / ADR-0010): the OCR step runs in the CLI before this
    function is called; the agent receives the detected exams as plain text
    and never sees the image bytes. This eliminates the "LLM fabricates
    base64" failure mode documented in ADR-0010.

    Args:
        exams: Exam names already extracted and PII-masked by the OCR server.
        correlation_id: UUID to propagate as X-Correlation-ID.

    Returns:
        Final ADK Event or None.
    """
    from google.adk.runners import Runner  # noqa: PLC0415
    from google.adk.sessions import InMemorySessionService  # noqa: PLC0415

    from generated_agent.agent import _build_agent  # noqa: PLC0415

    agent = _build_agent(correlation_id)
    toolsets = [t for t in agent.tools if hasattr(t, "close")]

    session_service = InMemorySessionService()
    runner = Runner(
        agent=agent,
        app_name="medical_order_agent",
        session_service=session_service,
    )
    session = await session_service.create_session(
        app_name="medical_order_agent",
        user_id="cli-user",
    )

    prompt_content = _build_preocr_prompt(exams)

    _LOGGER.info(
        "agent.run.start",
        extra={
            "event": "agent.run.start",
            "correlation_id": correlation_id,
            "exam_count": len(exams),
        },
    )

    final_response = None
    try:  # MAJOR-4: try/finally for session cleanup
        async for event in runner.run_async(
            user_id="cli-user",
            session_id=session.id,
            new_message=prompt_content,
        ):
            if hasattr(event, "is_final_response") and event.is_final_response():
                final_response = event
                break
    finally:
        # MAJOR-4: close MCP toolsets regardless of success/timeout/error
        for toolset in toolsets:
            try:
                await toolset.close()
            except Exception:  # noqa: BLE001
                pass  # cleanup errors must not mask the original exception
        # InMemorySessionService has no persistent resources — no delete needed.
        # If a persistent session service is added, call delete_session() here.

    return final_response


def _parse_runner_output(raw: Any, correlation_id: str) -> RunnerSuccess:
    """Parse and validate runner output against the RunnerResult union.

    Dispatches the raw event through three branches (spec 0009 Camada B):
      - RunnerSuccess -> returned for the caller to format as ASCII table
      - RunnerError   -> SystemExit(4) with the envelope on stderr (AC4)
      - malformed     -> SystemExit(3) with E_AGENT_OUTPUT_INVALID (AC6)

    A markdown fence wrapper (``` ```json ```) is tolerated via
    _strip_json_fence before json.loads — mitigates the gemini-2.5-pro drift
    documented in the 2026-04-21 addendum.

    Args:
        raw: Raw runner result (ADK Event, dict, or string).
        correlation_id: UUID for logging and envelope traceability.

    Returns:
        Validated RunnerSuccess (RunnerError branches exit the process).

    Raises:
        SystemExit(3): JSON/Pydantic validation failed.
        SystemExit(4): agent reported a structured error envelope.
    """
    text: str = ""
    if hasattr(raw, "content") and hasattr(raw.content, "parts"):
        for part in raw.content.parts:
            if hasattr(part, "text"):
                text += part.text
    elif isinstance(raw, str):
        text = raw
    else:
        text = str(raw) if raw is not None else ""

    stripped = _strip_json_fence(text)

    try:
        data = json.loads(stripped)
        result = RunnerResultAdapter.validate_python(data)
    except (json.JSONDecodeError, pydantic.ValidationError) as exc:
        _LOGGER.error(
            "agent.output.invalid",
            extra={
                "event": "agent.output.invalid",
                "correlation_id": correlation_id,
                "error": str(exc),
            },
        )
        _exit_error(
            code=_E_AGENT_OUTPUT_INVALID,
            message="Saida do agente nao corresponde ao schema esperado.",
            correlation_id=correlation_id,
            hint="Verifique se o agente retornou JSON valido com status='success' ou status='error'.",
            exit_code=3,
        )

    if isinstance(result, RunnerError):
        _LOGGER.error(
            "agent.output.reported_error",
            extra={
                "event": "agent.output.reported_error",
                "correlation_id": correlation_id,
                "agent_error_code": result.error.code,
            },
        )
        _exit_error(
            code=_E_AGENT_OUTPUT_REPORTED_ERROR,
            message=result.error.message,
            correlation_id=correlation_id,
            hint=result.error.hint,
            exit_code=4,
        )

    return result


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    """CLI entry point for the generated agent runner.

    Returns:
        Exit code (0 on success).
    """
    configure_logging()
    args = _parse_args()
    correlation_id = str(uuid.uuid4())

    # Read image bytes (MAJOR-3: use correct error code for missing file)
    image_path = args.image
    if not os.path.isfile(image_path):
        _exit_error(
            code=_E_AGENT_INPUT_NOT_FOUND,
            message=f"Arquivo de imagem nao encontrado: {image_path}",
            correlation_id=correlation_id,
            hint="Verifique o caminho passado em --image.",
            exit_code=1,
        )

    with open(image_path, "rb") as fh:
        image_bytes = fh.read()

    # Pre-OCR step (spec 0010 / ADR-0010): CLI orchestrates the OCR call
    # deterministically before the LlmAgent sees anything. If this fails, the
    # agent is never invoked.
    try:
        exams = asyncio.run(
            _run_preocr(
                image_bytes=image_bytes,
                correlation_id=correlation_id,
                mcp_url=_OCR_MCP_URL,
                timeout_s=_PREOCR_MCP_TIMEOUT,
                connect_retries=_PREOCR_MCP_CONNECT_RETRIES,
            )
        )
    except _PreOcrError as exc:
        if exc.code == _E_MCP_UNAVAILABLE:
            _exit_error(
                code=_E_MCP_UNAVAILABLE,
                message=exc.message,
                correlation_id=correlation_id,
                hint=exc.hint,
                exit_code=5,
            )
        _exit_error(
            code=exc.code,
            message=exc.message,
            correlation_id=correlation_id,
            hint=exc.hint,
            exit_code=4,
        )

    if not exams:
        _exit_error(
            code=_E_OCR_UNKNOWN_IMAGE,
            message="OCR nao retornou exames para a imagem fornecida.",
            correlation_id=correlation_id,
            hint="Verifique se a imagem corresponde a uma fixture registrada no ocr-mcp.",
            exit_code=4,
        )

    # Run agent with hard timeout (ADR-0008 / AC18)
    try:
        raw = asyncio.run(
            asyncio.wait_for(
                _run_agent(exams, correlation_id),
                timeout=_AGENT_TIMEOUT,
            )
        )
    except TimeoutError:  # MINOR-7: TimeoutError is the 3.12 alias for asyncio.TimeoutError
        _LOGGER.error(
            "agent.timeout",
            extra={"event": "agent.timeout", "correlation_id": correlation_id},
        )
        _exit_error(
            code=_E_AGENT_TIMEOUT,
            message=f"Agente excedeu o tempo limite de {int(_AGENT_TIMEOUT)} s.",
            correlation_id=correlation_id,
            hint="Verifique se os servicos MCP estao saudaveis (docker compose ps).",
            exit_code=2,
        )

    output = _parse_runner_output(raw, correlation_id)

    rows = [
        (exam.name, exam.code, exam.score, exam.inconclusive)
        for exam in output.exams
    ]
    table = format_ascii_table(rows, output.appointment_id, output.scheduled_for)
    print(table)

    _LOGGER.info(
        "agent.run.done",
        extra={
            "event": "agent.run.done",
            "correlation_id": correlation_id,
            "appointment_id": output.appointment_id,
            "exam_count": len(output.exams),
        },
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
