"""medical-order-agent runner CLI — generated by transpiler."""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import logging
import mimetypes
import os
import re
import sys
import typing
import uuid
from datetime import datetime
from typing import Any

import pydantic
from pydantic import BaseModel, field_validator

from generated_agent.logging_ import configure_logging

_LOGGER = logging.getLogger(__name__)

_AGENT_TIMEOUT = float(os.environ.get("AGENT_TIMEOUT_SECONDS", "300"))  # seconds, ADR-0008 / AC18

# Error code constants (MAJOR-3)
_E_AGENT_INPUT_NOT_FOUND = "E_AGENT_INPUT_NOT_FOUND"
_E_AGENT_OUTPUT_INVALID = "E_AGENT_OUTPUT_INVALID"
_E_AGENT_TIMEOUT = "E_AGENT_TIMEOUT"


# ---------------------------------------------------------------------------
# Output schema — validates LLM runner result before printing (AC19)
# ---------------------------------------------------------------------------


class ExamResolution(BaseModel):
    """Single exam resolved by the agent."""

    name: str
    code: str
    score: float
    inconclusive: bool = False

    @field_validator("score")
    @classmethod
    def score_in_range(cls, v: float) -> float:
        """Validate score is in [0.0, 1.0]."""
        if not (0.0 <= v <= 1.0):
            msg = f"score must be in [0.0, 1.0], got {v}"
            raise ValueError(msg)
        return v


class _RunnerOutput(BaseModel):
    """Expected structure of the agent's final output (AC19)."""

    exams: list[ExamResolution]
    appointment_id: str
    scheduled_for: datetime


# ---------------------------------------------------------------------------
# ASCII table formatter (AC17) — pure function, no Rich, no ANSI
# ---------------------------------------------------------------------------


def format_ascii_table(
    rows: list[tuple[str, str, float, bool]],
    appointment_id: str,
    scheduled_for: datetime | str,
) -> str:
    """Format exam results as a plain ASCII table.

    Args:
        rows: List of (name, code, score, inconclusive) tuples.
        appointment_id: Scheduling API appointment ID.
        scheduled_for: Scheduled datetime (datetime or ISO string).

    Returns:
        Multi-line ASCII string in the exact format required by AC17.
    """
    col_widths = [3, 22, 9]  # #, Exame, Codigo — minimum widths
    for i, (name, code, _, _) in enumerate(rows):
        col_widths[0] = max(col_widths[0], len(str(i + 1)))
        col_widths[1] = max(col_widths[1], len(name))
        col_widths[2] = max(col_widths[2], len(code))

    def _sep() -> str:
        return (
            "+"
            + "-" * (col_widths[0] + 2)
            + "+"
            + "-" * (col_widths[1] + 2)
            + "+"
            + "-" * (col_widths[2] + 2)
            + "+"
        )

    def _row(a: str, b: str, c: str) -> str:
        return (
            "| "
            + a.ljust(col_widths[0])
            + " | "
            + b.ljust(col_widths[1])
            + " | "
            + c.ljust(col_widths[2])
            + " |"
        )

    lines: list[str] = [
        _sep(),
        _row("#", "Exame", "Codigo"),
        _sep(),
    ]
    for i, (name, code, score, inconclusive) in enumerate(rows):
        label = code if not inconclusive else f"{code}?"
        lines.append(_row(str(i + 1), name, label))
    lines.append(_sep())

    sched_str = (
        scheduled_for.isoformat()
        if isinstance(scheduled_for, datetime)
        else str(scheduled_for)
    )
    lines.append(f"Appointment ID: {appointment_id}  |  Scheduled: {sched_str}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Error helpers (MAJOR-1)
# ---------------------------------------------------------------------------


def _exit_error(
    code: str,
    message: str,
    correlation_id: str,
    hint: str | None = None,
    exit_code: int = 1,
) -> typing.NoReturn:
    """Print canonical error envelope to stderr and exit.

    Envelope shape matches ADR-0008 / scheduling_api ErrorEnvelope:
        {"error": {"code": ..., "message": ..., "hint": ...}, "correlation_id": ...}

    Args:
        code: E_* error code per ADR-0008.
        message: Human-readable error message.
        correlation_id: UUID from main() scope for traceability.
        hint: Optional corrective-action hint.
        exit_code: Process exit code (1=input, 2=timeout, 3=output, default=1).
    """
    envelope: dict[str, Any] = {
        "error": {
            "code": code,
            "message": message,
            "hint": hint,
        },
        "correlation_id": correlation_id,
    }
    print(json.dumps(envelope, ensure_ascii=False), file=sys.stderr)
    sys.exit(exit_code)


# ---------------------------------------------------------------------------
# Argument parser (MINOR-9: --spec removed — not wired up)
# ---------------------------------------------------------------------------


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments.

    Returns:
        Parsed namespace with .image attribute.
    """
    parser = argparse.ArgumentParser(
        description="medical-order-agent — ADK agent runner (generated by transpiler)",
    )
    parser.add_argument(
        "--image",
        required=True,
        help="Path to the medical order image (PNG/JPEG).",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Agent runner (BLOCKER-1: inline_data Blob, BLOCKER-2: factory, MAJOR-4: cleanup)
# ---------------------------------------------------------------------------


async def _run_agent(image_bytes: bytes, correlation_id: str, mime_type: str = "image/png") -> Any:
    """Run the ADK agent with raw image bytes as an inline_data Part.

    Builds the agent via _build_agent(correlation_id) so every MCP connection
    carries X-Correlation-ID. Image is transmitted as genai_types.Part with
    inline_data Blob — NOT as a text/base64 part — so PII callback only
    iterates legitimate text parts (BLOCKER-1).

    Args:
        image_bytes: Raw bytes of the image file.
        correlation_id: UUID to propagate as X-Correlation-ID.

    Returns:
        Final ADK Event or None.
    """
    from google.adk.runners import Runner  # noqa: PLC0415
    from google.adk.sessions import InMemorySessionService  # noqa: PLC0415
    from google.genai import types as genai_types  # noqa: PLC0415

    from generated_agent.agent import _build_agent  # noqa: PLC0415

    agent = _build_agent(correlation_id)
    toolsets = [t for t in agent.tools if hasattr(t, "close")]

    session_service = InMemorySessionService()
    runner = Runner(
        agent=agent,
        app_name="medical_order_agent",  # ADK requires valid Python identifier
        session_service=session_service,
    )
    session = await session_service.create_session(
        app_name="medical_order_agent",
        user_id="cli-user",
    )

    # BLOCKER-1: image as inline_data Blob so the PII callback only sees
    # legitimate text parts, not a base64 string masquerading as text.
    image_part = genai_types.Part.from_bytes(
        data=image_bytes,
        mime_type=mime_type,
    )
    instruction_part = genai_types.Part(
        text="Processe o pedido medico na imagem fornecida e siga o plano fixo."
    )
    prompt_content = genai_types.Content(
        role="user",
        parts=[image_part, instruction_part],
    )

    _LOGGER.info(
        "agent.run.start",
        extra={
            "event": "agent.run.start",
            "correlation_id": correlation_id,
            "image_sha256_prefix": hashlib.sha256(image_bytes).hexdigest()[:8],
        },
    )

    final_response = None
    last_text_event = None
    try:  # MAJOR-4: try/finally for session cleanup
        async for event in runner.run_async(
            user_id="cli-user",
            session_id=session.id,
            new_message=prompt_content,
        ):
            if _event_has_text(event):
                last_text_event = event
            if hasattr(event, "is_final_response") and event.is_final_response():
                final_response = event
                break
    finally:
        # MAJOR-4: close MCP toolsets regardless of success/timeout/error
        for toolset in toolsets:
            try:
                await toolset.close()
            except Exception:  # noqa: BLE001
                pass  # cleanup errors must not mask the original exception
        # InMemorySessionService has no persistent resources — no delete needed.
        # If a persistent session service is added, call delete_session() here.

    # If the final event carried only tool_calls / no text, fall back to the
    # last event that did carry text. Gemini sometimes flags a function-call
    # event as final before emitting the post-call text in a trailing event.
    if final_response is not None and not _event_has_text(final_response) and last_text_event is not None:
        _LOGGER.info(
            "agent.final.fallback_to_last_text",
            extra={"event": "agent.final.fallback_to_last_text", "correlation_id": correlation_id},
        )
        return last_text_event
    return final_response if final_response is not None else last_text_event


def _event_has_text(event: Any) -> bool:
    """Return True if the event carries at least one non-empty text part."""
    content = getattr(event, "content", None)
    parts = getattr(content, "parts", None) if content is not None else None
    if not parts:
        return False
    for part in parts:
        part_text = getattr(part, "text", None)
        if isinstance(part_text, str) and part_text.strip():
            return True
    return False


_JSON_FENCE_RE = re.compile(r"^\s*```(?:json)?\s*(.*?)\s*```\s*$", re.DOTALL | re.IGNORECASE)


def _strip_json_fence(text: str) -> str:
    """Remove ```json ... ``` fences if the model wrapped its reply in one.

    The instruction tells the model not to use code fences, but Gemini still
    emits them occasionally. If a fence is not present, the text is returned
    unchanged. Also extracts the first {...} block if surrounded by prose.
    """
    if not text:
        return text
    stripped = text.strip()
    match = _JSON_FENCE_RE.match(stripped)
    if match:
        return match.group(1).strip()
    # If response isn't pure JSON but contains one, extract the outermost {...}.
    if not stripped.startswith("{"):
        first = stripped.find("{")
        last = stripped.rfind("}")
        if first != -1 and last != -1 and last > first:
            return stripped[first : last + 1]
    return stripped


def _parse_runner_output(raw: Any, correlation_id: str) -> _RunnerOutput:
    """Parse and validate runner output against the expected schema.

    Args:
        raw: Raw runner result (Event or dict or string).
        correlation_id: For logging.

    Returns:
        Validated _RunnerOutput instance.

    Raises:
        SystemExit(3): when JSON or Pydantic validation fails (AC19).
    """
    text: str = ""
    if hasattr(raw, "content") and hasattr(raw.content, "parts") and raw.content is not None:
        for part in raw.content.parts or []:
            part_text = getattr(part, "text", None)
            if isinstance(part_text, str):
                text += part_text
    elif isinstance(raw, str):
        text = raw
    else:
        text = str(raw) if raw is not None else ""

    text = _strip_json_fence(text)

    # MAJOR-2: narrow exception catch — only JSON/Pydantic failures are expected
    try:
        data = json.loads(text)
        output = _RunnerOutput.model_validate(data)
    except (json.JSONDecodeError, pydantic.ValidationError) as exc:
        _LOGGER.error(
            "agent.output.invalid",
            extra={
                "event": "agent.output.invalid",
                "correlation_id": correlation_id,
                "error": str(exc),
            },
        )
        _exit_error(
            code=_E_AGENT_OUTPUT_INVALID,
            message="Saida do agente nao corresponde ao schema esperado.",
            correlation_id=correlation_id,
            hint=(
                "Verifique se o agente retornou JSON valido com campos "
                "exams[], appointment_id, scheduled_for."
            ),
            exit_code=3,
        )
        # MINOR-2: unreachable raise removed — _exit_error is NoReturn

    return output


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    """CLI entry point for the generated agent runner.

    Returns:
        Exit code (0 on success).
    """
    configure_logging()
    args = _parse_args()
    correlation_id = str(uuid.uuid4())

    image_path = args.image
    if not os.path.isfile(image_path):
        _exit_error(
            code=_E_AGENT_INPUT_NOT_FOUND,  # MAJOR-3: correct error code for missing file
            message=f"Arquivo de imagem nao encontrado: {image_path}",
            correlation_id=correlation_id,
            hint="Verifique o caminho passado em --image.",
            exit_code=1,
        )

    with open(image_path, "rb") as fh:
        image_bytes = fh.read()

    guessed_mime, _ = mimetypes.guess_type(image_path)
    image_mime = guessed_mime or "image/png"

    # Run agent with hard timeout (ADR-0008 / AC18)
    try:
        raw = asyncio.run(
            asyncio.wait_for(
                _run_agent(image_bytes, correlation_id, image_mime),
                timeout=_AGENT_TIMEOUT,
            )
        )
    except TimeoutError:  # MINOR-7: TimeoutError is the 3.12 alias for asyncio.TimeoutError
        _LOGGER.error(
            "agent.timeout",
            extra={"event": "agent.timeout", "correlation_id": correlation_id},
        )
        _exit_error(
            code=_E_AGENT_TIMEOUT,
            message=f"Agente excedeu o tempo limite de {int(_AGENT_TIMEOUT)} s.",
            correlation_id=correlation_id,
            hint="Verifique se os servicos MCP estao saudaveis (docker compose ps).",
            exit_code=2,
        )

    output = _parse_runner_output(raw, correlation_id)

    rows = [
        (exam.name, exam.code, exam.score, exam.inconclusive)
        for exam in output.exams
    ]
    table = format_ascii_table(rows, output.appointment_id, output.scheduled_for)
    print(table)

    _LOGGER.info(
        "agent.run.done",
        extra={
            "event": "agent.run.done",
            "correlation_id": correlation_id,
            "appointment_id": output.appointment_id,
            "exam_count": len(output.exams),
        },
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
