"""medical-order-agent agent — generated by transpiler.

NOTE (ADK real-world finding):
    OpenAPIToolset does NOT accept a spec_url parameter in the installed version
    of google-adk. It requires spec_dict or spec_str. The scheduling toolset
    is therefore initialised lazily inside _build_agent() via _load_scheduling_toolset(),
    which fetches the OpenAPI spec from the SCHEDULING_OPENAPI_URL environment
    variable using httpx. The template (agent.py.j2) matches this pattern.

NOTE (adk web / adk run dev-server):
    The `root_agent` module-level variable is kept for `adk web` / `adk run`
    dev-server discovery. It is initialised with correlation_id="boot" — not
    for production use. Production callers use _build_agent(correlation_id).
    The ADK service name convention uses hyphens; Python module uses underscores.
    Noted as MINOR-1 in review; no action taken per brief.
"""

from __future__ import annotations

import json
import logging
import os

from collections.abc import Callable
from typing import Any

from urllib.parse import urlparse

import httpx
from google.adk.agents import LlmAgent
from google.adk.tools.base_tool import BaseTool
from google.adk.tools.base_toolset import BaseToolset
from google.adk.tools.mcp_tool import McpToolset
from google.adk.tools.mcp_tool.mcp_session_manager import SseConnectionParams
from google.adk.tools.openapi_tool.openapi_spec_parser.openapi_toolset import OpenAPIToolset
from security import make_pii_callback

_LOGGER = logging.getLogger(__name__)

_ToolItem = Callable[..., Any] | BaseTool | BaseToolset

_SSE_HEADERS: dict[str, str] = {
    "Accept": "application/json, text/event-stream",
}

_SCHEDULING_OPENAPI_URL = os.environ.get(
    "SCHEDULING_OPENAPI_URL",
    "http://scheduling-api:8000/openapi.json",
)
_GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash-lite")
_SPEC_FETCH_TIMEOUT_SECONDS = float(
    os.environ.get("SCHEDULING_OPENAPI_FETCH_TIMEOUT_SECONDS", "10")
)


def _load_scheduling_toolset(correlation_id: str) -> OpenAPIToolset:
    """Fetch the scheduling API's OpenAPI spec and return a toolset.

    Called inside _build_agent() so the agent module can be imported without a
    live scheduling-api service. At runtime, the service must be reachable.

    The X-Correlation-ID header is passed on the spec-fetch call.
    OpenAPIToolset itself does not natively propagate request headers to each
    tool invocation — a code comment below documents this limitation.

    Args:
        correlation_id: UUID to include in the spec-fetch request header.

    Returns:
        OpenAPIToolset initialised with the fetched spec_dict.

    Raises:
        httpx.ConnectError: if the spec URL is unreachable.
        httpx.ConnectTimeout: if the spec URL connection times out.
    """
    resp = httpx.get(
        _SCHEDULING_OPENAPI_URL,
        timeout=_SPEC_FETCH_TIMEOUT_SECONDS,
        headers={"X-Correlation-ID": correlation_id},
    )
    resp.raise_for_status()
    spec_dict = resp.json()
    # NOTE: OpenAPIToolset does not forward per-request headers to tool calls.
    # The X-Correlation-ID is passed on the spec fetch only; tool calls will
    # not carry it. This is an ADK limitation (BLOCKER-2 partial mitigation).
    # FastAPI does not emit a `servers` entry by default; without it the
    # OpenAPIToolset constructs requests with only the path and httpx rejects
    # them with UnsupportedProtocol. Derive the base URL from the spec URL
    # itself so the fix works for any spec that omits `servers`.
    if not spec_dict.get("servers"):
        parsed = urlparse(_SCHEDULING_OPENAPI_URL)
        spec_dict["servers"] = [{"url": f"{parsed.scheme}://{parsed.netloc}"}]
    return OpenAPIToolset(spec_dict=spec_dict)


def _build_agent(correlation_id: str) -> LlmAgent:
    """Build and return the LlmAgent wired with all toolsets.

    Constructs McpToolset instances with X-Correlation-ID injected into SSE
    headers so every MCP call is traceable end-to-end.

    Args:
        correlation_id: UUID generated at CLI startup. Injected into all
            outbound SSE and HTTP headers.

    Returns:
        Fully configured LlmAgent ready for Runner.
    """
    _corr_headers = {**_SSE_HEADERS, "X-Correlation-ID": correlation_id}

    ocr_toolset = McpToolset(
        connection_params=SseConnectionParams(
            url=os.environ.get("OCR_MCP_URL", "http://ocr-mcp:8001/sse"),
            headers=_corr_headers,
        ),
        tool_filter=["extract_exams_from_image"],
    )

    rag_toolset = McpToolset(
        connection_params=SseConnectionParams(
            url=os.environ.get("RAG_MCP_URL", "http://rag-mcp:8002/sse"),
            headers=_corr_headers,
        ),
        tool_filter=["search_exam_code", "list_exams"],
    )

    tools: list[_ToolItem] = [ocr_toolset, rag_toolset]

    try:
        scheduling_toolset: OpenAPIToolset | None = _load_scheduling_toolset(correlation_id)
    except (httpx.ConnectError, httpx.ConnectTimeout) as exc:
        _LOGGER.warning(
            "scheduling.toolset.unavailable",
            extra={
                "event": "scheduling.toolset.unavailable",
                "correlation_id": correlation_id,
                "error": str(exc),
            },
        )
        scheduling_toolset = None

    if scheduling_toolset is not None:
        tools.append(scheduling_toolset)

    return LlmAgent(
        name="medical_order_agent",  # ADK requires valid Python identifier — hyphens not allowed
        model=_GEMINI_MODEL,
        description="Agente de agendamento de exames a partir de pedidos medicos digitalizados",
        instruction=(
            "Voce e um agente de agendamento de exames medicos. Siga o plano abaixo na ordem exata.\n\n"
            "PLANO FIXO (plan-then-execute):\n"
            "1. Chame extract_exams_from_image(image_base64) UMA VEZ para obter a lista de exames. NAO repita esta chamada.\n"
            "2. Para cada exame retornado, chame search_exam_code EM PARALELO (emita multiplas tool calls na mesma resposta).\n"
            "3. Monte uma lista interna [(nome, codigo, score)] - NAO formate a saida ainda.\n"
            "4. Se search_exam_code retornar null ou score < 0.80: chame list_exams(limit=20) UMA vez, escolha o candidato mais proximo, marque inconclusive=true e prossiga. NAO pergunte ao usuario - nao ha usuario interativo.\n"
            "5. Faca UM UNICO POST /api/v1/appointments com todos os exames no campo exams[]. Use patient_ref='anon-<hash>' (invente um hash curto). Leia appointment_id e scheduled_for da resposta.\n"
            "6. SAIDA FINAL: responda APENAS com um unico objeto JSON valido, sem markdown, sem cercas de codigo, sem texto antes ou depois. Schema obrigatorio:\n"
            "{\"exams\": [{\"name\": \"<nome>\", \"code\": \"<codigo>\", \"score\": <float 0..1>, \"inconclusive\": <bool>}, ...], \"appointment_id\": \"<id retornado pela API>\", \"scheduled_for\": \"<ISO-8601 retornado pela API>\"}\n"
            "Nao inclua nenhum outro campo. Nao use ```json. Retorne SOMENTE o objeto JSON.\n\n"
            "POLITICA DE ERROS (congelada):\n"
            "- E_MCP_TIMEOUT: 1 retry com delay fixo de 500ms; se persistir, propague erro com hint 'Verifique docker compose ps' e aborte.\n"
            "- E_RAG_NO_MATCH (null ou score<0.80): zero retry. Chame list_exams(limit=20), pegue o candidato mais proximo, marque inconclusive=true.\n"
            "- E_API_VALIDATION (422): zero retry - agendamento duplicado e inaceitavel. Reporte campo + motivo da mensagem Pydantic.\n\n"
            "RESTRICOES:\n"
            "- NUNCA inclua nomes, CPFs ou telefones no JSON final. Use <PERSON>, <CPF> conforme recebidos.\n"
            "- patient_ref e SEMPRE anon-<hash>. Nunca invente nomes reais.\n"
            "- Registre cada chamada de tool com params_hash e correlation_id para rastreabilidade."
        ),
        tools=tools,
        before_model_callback=make_pii_callback(allow_list=[]),
    )


# Module-level root_agent for `adk web` / `adk run` dev-server discovery.
# LAZY: built on first attribute access so `import generated_agent.agent` does
# not trigger a 10s blocking httpx.get at import time (MAJOR-5 round-2 fix).
# Production entry point uses _build_agent(correlation_id) from main().
def __getattr__(name: str) -> Any:
    if name == "root_agent":
        agent = _build_agent("boot")
        globals()["root_agent"] = agent
        return agent
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
