"""medical-order-agent structured logging — generated by transpiler."""

from __future__ import annotations

import hashlib
import json
import logging
import os
import time


class _JsonFormatter(logging.Formatter):
    """Format log records as single-line JSON objects (ADR-0008 § Formato de log).

    Fields emitted:
        timestamp, level, service, event, correlation_id (when present),
        plus any key=value pairs in record.extra.

    Invariant (AC21):
        No raw PII values are emitted. Callers must pass only params_hash,
        sha256_prefix, entity_type, duration_ms, correlation_id, etc.
    """

    SERVICE = "medical-order-agent"

    def format(self, record: logging.LogRecord) -> str:
        """Serialize a LogRecord to a JSON line.

        Args:
            record: Standard LogRecord instance.

        Returns:
            JSON-encoded string without a trailing newline.
        """
        payload: dict[str, object] = {
            "timestamp": self.formatTime(record, self.datefmt),
            "level": record.levelname,
            "service": self.SERVICE,
            "logger": record.name,
            "message": record.getMessage(),
        }
        # Copy extra fields attached by the caller
        for key, value in record.__dict__.items():
            if key not in _JSON_SKIP_FIELDS:
                payload[key] = value
        return json.dumps(payload, default=str, ensure_ascii=False)


_JSON_SKIP_FIELDS = frozenset(
    {
        "args",
        "created",
        "exc_info",
        "exc_text",
        "filename",
        "funcName",
        "levelname",
        "levelno",
        "lineno",
        "message",
        "module",
        "msecs",
        "msg",
        "name",
        "pathname",
        "process",
        "processName",
        "relativeCreated",
        "stack_info",
        "taskName",
        "thread",
        "threadName",
    }
)


def configure_logging() -> None:
    """Configure root logger with JSON formatter for this agent.

    Reads LOG_LEVEL from environment (default: INFO).
    """
    level_name = os.environ.get("LOG_LEVEL", "INFO").upper()
    level = getattr(logging, level_name, logging.INFO)
    handler = logging.StreamHandler()
    handler.setFormatter(_JsonFormatter())
    root = logging.getLogger()
    root.setLevel(level)
    if not root.handlers:
        root.addHandler(handler)
    else:
        root.handlers[0] = handler


def params_hash(params: object) -> str:
    """Return the first 16 hex chars of SHA-256 of the JSON-serialised params.

    This is the canonical way to log tool call arguments without emitting
    raw PII (AC11, parameter inspection pattern).

    Args:
        params: Any JSON-serialisable object representing tool call parameters.

    Returns:
        16-character lowercase hex string.
    """
    serialised = json.dumps(params, default=str, sort_keys=True)
    return hashlib.sha256(serialised.encode("utf-8")).hexdigest()[:16]


class ToolCallLogger:
    """Context manager that logs event=tool.called with timing and params_hash.

    Usage:
        with ToolCallLogger("search_exam_code", {"exam_name": "Hemograma"}, cid) as tcl:
            result = await mcp_tool(exam_name="Hemograma")
        # On exit, emits: event=tool.called, tool, params_hash, duration_ms, correlation_id

    Invariant (AC21):
        Only params_hash (not raw params) is logged.
    """

    _logger = logging.getLogger("tool")

    def __init__(self, tool_name: str, params: object, correlation_id: str = "") -> None:
        """Initialise logger.

        Args:
            tool_name: Name of the tool being called.
            params: Tool call parameters (JSON-serialisable).
            correlation_id: Propagated correlation identifier.
        """
        self._tool = tool_name
        self._hash = params_hash(params)
        self._cid = correlation_id
        self._start: float = 0.0

    def __enter__(self) -> "ToolCallLogger":
        """Record start time."""
        self._start = time.monotonic()
        return self

    def __exit__(self, *_: object) -> None:
        """Emit tool.called log entry."""
        duration_ms = (time.monotonic() - self._start) * 1000
        self._logger.info(
            "tool.called",
            extra={
                "event": "tool.called",
                "tool": self._tool,
                "params_hash": self._hash,
                "duration_ms": round(duration_ms, 2),
                "correlation_id": self._cid,
            },
        )
